import Example from "@frontend/components/Example";
import Head from "next/head";

import type { NextPage } from "next";
import { Button } from "@mui/material";

const Home: NextPage = () => {
  return (
    <div className="w-8/12 mx-auto mt-24">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white">
        <Button>Text</Button>
        <Example />
        <p className="text-2xl">The quick brown fox ...</p>
      </main>

      <footer className="w-full">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
        </a>
      </footer>
    </div>
  );
};

export default Home;
